application: willnevergrowup-1273
version: 2
runtime: php55
api_version: 1
threadsafe: no

handlers:
- url: /favicon\.ico
  static_files: favicon.ico
  upload: favicon\.ico

- url: /(.+\.(gif|png|jpg|css|js|html|eot|woff|ttf|svg|otf|xml|txt|json|swf))$
  static_files: \1
  upload: .+\.(gif|png|jpg|css|js|html|eot|woff|ttf|svg|otf|xml|txt|json|swf)$
  application_readable: true

- url: /CRISIL
  script: /CRISIL/index.php

- url: /.*
  script: index.php


